
service: import-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-central-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action: "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::kirv-import-service-bucket"
        - Effect: Allow
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::kirv-import-service-bucket/*"
        - Effect: Allow
          Action: sqs:*
          Resource: arn:aws:sqs:eu-central-1:750769084493:productQueue

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
     - httpApi:
        path: /import
        method: get
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: kirv-import-service-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

